services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: microsoft-todo-backend

    env_file:
      - ./backend/.env

    ports:
      - "8080:8080"

    volumes:
      - ./backend/uploads:/app/uploads

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: microsoft-todo-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped